name: ci cd

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:
env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

permissions:
  contents: read
  pull-requests: write
jobs:

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: terraform fmt check
        uses: dflook/terraform-fmt-check@v2

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.10.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Tests
        run: terraform test

  validate:
    name: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Terraform Validate
        uses: dflook/terraform-validate@v2


  plan:
    if: github.event_name == 'pull_request'
    needs: [lint, test, validate]
    name: plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: terraform plan
        uses: dflook/terraform-plan@v2
        with:
          var_file: dev.tfvars

  pre-cost-analysis:
    needs: plan
    name: Pre cost analysis
    runs-on: ubuntu-latest
    steps:

      - name: Infracost Actions
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}


      - name: Checkout Base Branch
        uses: actions/checkout@v4
        with:
          ref: '${{ github.event.pull_request.base.ref }}'

      - name : HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.10.0

      - name: run init
        run: terraform init

      - name: Generate Infracost cost estimate baseline
        run: |
          infracost breakdown --path=. \
                                 --format=json \
                                 --out-file=/tmp/infracost-base.json \
                                 --terraform-var-file=dev.tfvars

      - name: Debug workspace
        run: ls -R

      - name: Checkout Pr Branch
        uses: actions/checkout@v4

      - name: Debug workspace
        run: ls -R

      - name: Generate Infracost diff
        run: |
          infracost diff --path=. \
                          --format=json \
                          --compare-to=/tmp/infracost-base.json \
                          --out-file=/tmp/infracost-diff.json


      - name: Post Infracost comment
        run: |
            infracost comment github --path=/tmp/infracost-diff.json \
                                     --repo=$GITHUB_REPOSITORY \
                                     --github-token=${{ github.token }} \
                                     --pull-request=${{ github.event.pull_request.number }} \
                                     --behavior=update



  apply:
    if: github.ref_name == 'main' && github.event_name == 'push'
    needs: [lint, test, validate]
    name: apply
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      # - name: HashiCorp - Setup Terraform
      #   uses: hashicorp/setup-terraform@v3.1.2
      #   with:
      #     terraform_version: 1.10.0

      # - name: run init
      #   run: terraform init

      # - name: run apply
      #   run: terraform apply -auto-approve -var-file=dev.tfvars


  post-cost-analysis:
    needs: apply
    name: Post cost analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Infracost Actions
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: generate cost report
        run: |
          infracost breakdown --path=. \
                                 --format=json \
                                 --out-file=/tmp/infracost.json \
                                 --terraform-var-file=dev.tfvars

      - name: upload cost report
        uses: actions/upload-artifact@v4.6.2
        with:
          name: infracost-report
          path: /tmp/infracost.json




          # destroy:
  #   if: github.event_name == 'push'
  #   needs: [apply]
  #   name: destroy
  #   runs-on: ubuntu-latest
  #   environment: production
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: HashiCorp - Setup Terraform
  #       uses: hashicorp/setup-terraform@v3.1.2
  #       with:
  #         terraform_version: 1.10.0

  #     - name: run destroy
  #       run: terraform destroy -auto-approve
