name: ci cd

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:
env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }} 
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

jobs:

  lint:    
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: log all env vars
        run: | 
          echo "ARM_CLIENT_ID:  {{ secrets.ARM_CLIENT_ID }}"
          echo "ARM_CLIENT_SECRET:  {{ secrets.ARM_CLIENT_SECRET }}"
          echo "ARM_TENANT_ID:  {{ secrets.ARM_TENANT_ID }}"
          echo "ARM_SUBSCRIPTION_ID:  {{ secrets.ARM_SUBSCRIPTION_ID }}"
          echo "INFRACOST_API_KEY:  {{ secrets.INFRACOST_API_KEY }}"
      
      - uses: actions/checkout@v4
      
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with: 
          terraform_version: 1.10.0

      - name: run fmt
        run: terraform fmt
     
  test:    
    name: test 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with: 
          terraform_version: 1.10.0

      - name: run init
        run: terraform init
    
      - name: run test
        run: terraform test

  validate:    
    name: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with: 
          terraform_version: 1.10.0
      
      - name: run init
        run: terraform init 

      - name: run validate
        run: terraform validate

  
  plan:
    if: github.event_name == 'pull_request'
    needs: [lint, test, validate]
    name: plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with: 
          terraform_version: 1.10.0
          
      - name: run init
        run: terraform init

      - name: run plan
        run: terraform plan

  
  cost-analysis-dev:
    needs: plan
    name: cost analysis dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Infracost Actions
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: generate cost report
        run: infracost breakdown --path=. \
                                 --format=json \
                                 --out-file=/tmp/infracost.json \
                                 --terraform-vars-file=dev.tfvars


        
  apply:
    if: github.ref_name == 'main' && github.event_name == 'push'
    needs: [lint, test, validate]
    name: apply
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      
      # - name: HashiCorp - Setup Terraform
      #   uses: hashicorp/setup-terraform@v3.1.2
      #   with: 
      #     terraform_version: 1.10.0
          
      # - name: run init
      #   run: terraform init

      # - name: run apply
      #   run: terraform apply -auto-approve -var-file=dev.tfvars

    
  cost-analysis-prod:
    needs: apply
    name: cost analysis prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Infracost Actions
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: generate cost report
        run: infracost breakdown --path=. \
                                 --format=json \
                                 --out-file=/tmp/infracost.json \
                                 --terraform-vars-file=dev.tfvars
      
      - name: upload cost report
        uses: actions/upload-artifact@v4.6.2
        with:
          name: infracost-report
          path: /tmp/infracost.json                          
 
 
 
 
          # destroy:
  #   if: github.event_name == 'push'
  #   needs: [apply]
  #   name: destroy
  #   runs-on: ubuntu-latest
  #   environment: production
  #   steps:
  #     - uses: actions/checkout@v4
      
  #     - name: HashiCorp - Setup Terraform
  #       uses: hashicorp/setup-terraform@v3.1.2
  #       with: 
  #         terraform_version: 1.10.0

  #     - name: run destroy
  #       run: terraform destroy -auto-approve
